// src/pages/projects/[slug].tsx
import type { NextPage } from 'next'
import { FaClock, FaDesktop, FaLink,  FaMedal, FaTasks, FaUserAstronaut, FaUsers, FaSteam, FaBook, FaWindows, FaDoorOpen } from "react-icons/fa"
import PageContainer from '../../components/page-container'
import { CardInner, CardOuter } from '../../components/card'
import { getProjectData, getProjectPaths } from '../api/projects-static'
import Badge from './../../components/badge';
import { Swiper, SwiperSlide } from 'swiper/react';
import {EffectFlip, Navigation, Pagination } from 'swiper/modules';
import { Project } from './../api/projects-static';

const iconClass= "text-primary inline ml-2 mb-1"
const iconButton= "text-primary ml-2 mb-1 text-white"
const iconMap : Record<string, JSX.Element> = {
    "Website": <div className="p-4 rounded-lg bg-primary"><FaLink /></div>,
    "Steam": <div style={{backgroundColor: '#2c4059'}} className={iconButton+" p-4 rounded-lg text-xl"}><FaSteam /></div>,
    "Paper": <div style={{backgroundColor: '#6189b9'}} className={iconButton+" p-4 rounded-lg text-xl"}><FaBook /></div>,
    "windows": <FaWindows className={iconClass+" text-primary ml-auto mr-auto"} />,
    "escape": <FaDoorOpen className={iconClass} />,
};


//TODO move to API
export async function getStaticPaths() {
    return {
        paths: await getProjectPaths(),
        fallback: false,
    };
}

interface ProjectProps {
    project: Project
}

export async function getStaticProps({ params }: any) {
    return {
      props: {
        project: await getProjectData(params.slug),
      },
    };
  }

const YouTubeEmbed = ({src} : any) => {
    return <iframe style={{maxWidth: "80%", margin: "auto", marginBottom: 30, height: "100%"}} title="YouTube video player" data-allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen className="w-full h-full sm:min-h-[300px]" src={src} >Failed to load video</iframe>
}

const ProjectPage: NextPage<ProjectProps> = ({project}) => {
  return <>
    <PageContainer title="Projects">
        <div className="w-full bg-black p-6">
            <h1 className="text-4xl">{project.title}</h1>
            <span className="text-xs text-[var(--primary)]"><a className="underline" href="/projects">projects</a> {">"} {project.slug}</span>
        </div>
        <div className="flex flex-col gap-4 lg:gap-2 lg:flex-row w-full sm:w-11/12 lg:w-10/12 mr-10 ml-10 mt-5 mb-5">
            <CardOuter override className="h-fit sm:flex-initial backdrop-blur-sm sm:min-w-[250px] w-full ml-auto mr-auto sm:w-full lg:w-[30%] ">
                <CardInner type="" className="flex flex-col p-0 pl-0 pt-0 pb-0 pr-0 text-left">
                    <h3 className="text-primary text-xs font-medium">Project Type
                        {iconMap[project.type_icon] || <FaDesktop className={iconClass} />}
                    </h3>
                    <p className="text-sm font-medium mb-5">{project.type}</p>
                    <h3 className="text-primary text-xs font-medium">My Roles
                        <FaUserAstronaut className={iconClass} />
                    </h3>
                    <p className="text-sm font-medium mb-5">{project.roles}</p>
                    <h3 className="text-primary text-xs font-medium">Team Size
                        <FaUsers className={iconClass} />
                    </h3>
                    <p className="text-md font-medium mb-5">{project.team_size}</p>
                    <h3 className="text-primary text-xs font-medium">Additional Responsibilities
                        <FaTasks className={iconClass} />
                    </h3>
                    <p className="text-sm font-medium mb-5">{project.responsibilities}</p>
                    <h3 className="text-primary text-xs font-medium">Timeline
                        <FaClock className={iconClass} />
                    </h3>
                    <p className="text-sm font-medium mb-5">{project.timeline}</p>
                    <h3 className="text-primary text-xs font-medium">Achievements
                        <FaMedal className={iconClass} />
                    </h3>
                    <ul className="text-sm font-medium mb-5">{project.achievements.map(a => {
                        return <li>• {a}</li>
                    })}</ul>

                </CardInner>
            </CardOuter>
            <CardOuter override reverse className="h-min sm:flex-initial backdrop-blur-sm sm:min-w-[500px] w-full ml-auto mr-auto sm:w-full lg:w-[66%] ">
                {/* <CardInner reverse type="T">
                    <span className="text-2xl">
                        {project.title}
                    </span>
                </CardInner>  */}
                <CardInner type="T" reverse>
                    <Swiper spaceBetween={50}
                            modules={[Navigation, Pagination, EffectFlip]}
                            mousewheel={true}
                            className="min-h-[200px]"
                            slidesPerView={1}
                            navigation
                            pagination={{ clickable: true }}
                            onSlideChange={() => console.log('slide change')}
                            onSwiper={(swiper) => console.log(swiper)}>
                        {project.media.map((t: any) => {
                            return <SwiperSlide className="flex flex-col items-center align-middle justify-center" key={t[0]}>
                                {t[0].includes("png") || t[0].includes("jpg") ? 
                                    <img style={{maxWidth: "80%", margin: "auto", marginBottom: 30}} src={t[0]} alt={t[1]} /> :
                                 t[0].includes("youtu") ? 
                                    <YouTubeEmbed src={t[0]}>Failed to load video</YouTubeEmbed> :
                                 "Unrecognized media type "+t[0]
                                }
                            </SwiperSlide>
                        })}
                    </Swiper>
                </CardInner>
                <CardInner reverse type="M">
                    <div className="m-4 flex flex-wrap text-xs">
                        <b className="text-md mt-auto mb-auto">Made With: </b>
                        {project.tags.map((t: any) => {
                            return <Badge key={t[0]} className="text-xs" bg={t[1]}>{t[0]}</Badge>
                        })}
                    </div>
                    <div className="md m-5 text-sm text-left" dangerouslySetInnerHTML={{__html: project.content}} />
                </CardInner>
                <CardInner reverse type="B" className="flex flex-row gap-4 justify-center">
                    {project.links.map((link: [string, string?]) => {
                        return <a className="hover:scale-110 hover:-translate-y-1" key={link[0]} href={link[1]}>{iconMap[link[0]] || link[0]}</a>
                    })}
                </CardInner>
            </CardOuter>
        </div>
    </PageContainer>
  </>
}

export default ProjectPage

// src/src/routes/projects/[slug]/+page.svelte
<script lang="ts">
  import type { PageData } from './$types';
  import { base } from '$app/paths';

  export let data: PageData;
  const { project } = data;

  const iconClass = 'text-primary inline ml-2 mb-1';
</script>

<svelte:head>
  <title>{project.title} – Projects – Mikel Matticoli</title>
</svelte:head>

<section class="w-full bg-black p-6">
  <h1 class="text-4xl">{project.title}</h1>
  <span class="text-xs text-[var(--primary)]">
    <a class="underline" href="{base}/projects">projects</a> &gt; {project.slug}
  </span>
</section>

<section class="flex flex-col gap-4 lg:gap-2 lg:flex-row w-full sm:w-11/12 lg:w-10/12 mr-10 ml-10 mt-5 mb-5">
  <!-- Left column -->
  <div class="h-fit backdrop-blur-sm sm:min-w-[250px] w-full ml-auto mr-auto sm:w-full lg:w-[30%] bg-[#121212CC] rounded-2xl p-5 text-left">
    <h3 class="text-primary text-xs font-medium flex items-center gap-2">
      Project Type
      <span class={iconClass}>💻</span>
    </h3>
    <p class="text-sm font-medium mb-5">{project.type}</p>

    <h3 class="text-primary text-xs font-medium flex items-center gap-2">
      My Roles
      <span class={iconClass}>🧑‍🚀</span>
    </h3>
    <p class="text-sm font-medium mb-5">{project.roles}</p>

    <h3 class="text-primary text-xs font-medium flex items-center gap-2">
      Team Size
      <span class={iconClass}>👥</span>
    </h3>
    <p class="text-md font-medium mb-5">{project.team_size}</p>

    <h3 class="text-primary text-xs font-medium flex items-center gap-2">
      Additional Responsibilities
      <span class={iconClass}>📝</span>
    </h3>
    <p class="text-sm font-medium mb-5">{project.responsibilities}</p>

    <h3 class="text-primary text-xs font-medium flex items-center gap-2">
      Timeline
      <span class={iconClass}>⏱️</span>
    </h3>
    <p class="text-sm font-medium mb-5">{project.timeline}</p>

    <h3 class="text-primary text-xs font-medium flex items-center gap-2">
      Achievements
      <span class={iconClass}>🏅</span>
    </h3>
    <ul class="text-sm font-medium mb-5 list-disc list-inside">
      {#each project.achievements as a}
        <li>{a}</li>
      {/each}
    </ul>
  </div>

  <!-- Right column -->
  <div class="h-min backdrop-blur-sm sm:min-w-[500px] w-full ml-auto mr-auto sm:w-full lg:w-[66%] bg-[#121212CC] rounded-2xl p-5">
    <!-- Media gallery (simplified: show all images stacked) -->
    <div class="mb-6 flex flex-col items-center gap-6">
      {#each project.media as media (media[0])}
        {#if media[0].includes('png') || media[0].includes('jpg')}
          <img
            class="max-w-[80%] mx-auto mb-4 rounded-md border-2"
            src={media[0]}
            alt={media[1] ?? project.title}
          />
        {:else if media[0].includes('youtu')}
          <iframe
            style="max-width: 80%; margin: auto; margin-bottom: 30px; height: 100%;"
            title="YouTube video player"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowfullscreen
            class="w-full h-full sm:min-h-[300px]"
            src={media[0]}
          >
            Failed to load video
          </iframe>
        {:else}
          <span>Unrecognized media type {media[0]}</span>
        {/if}
      {/each}
    </div>

    <div class="bg-[#2c2c2cCC] rounded-t-2xl rounded-b-none p-4 flex flex-wrap text-xs mb-2">
      <b class="text-md mt-auto mb-auto mr-2">Made With:</b>
      {#each project.tags as tag (tag[0])}
        <span
          class="m-1 px-2 py-1 rounded-sm text-xs font-semibold text-black"
          style={`background-color: ${tag[1]}`}
        >
          {tag[0]}
        </span>
      {/each}
    </div>

    <div class="bg-[#2c2c2cCC] rounded-none p-5 text-sm text-left">
      <div class="prose prose-invert">
        {@html project.content}
      </div>
    </div>

    <div class="bg-[#2c2c2cCC] rounded-b-2xl rounded-t-none p-4 flex flex-row gap-4 justify-center mt-2">
      {#each project.links as link (link[0])}
        <a class="hover:scale-110 hover:-translate-y-1 underline" href={link[1]}>
          {link[0]}
        </a>
      {/each}
    </div>
  </div>
</section>
